name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        
      - name: Upload SpotBugs Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: build/reports/spotbugs.html
